language: go
go:
  - "1.3.1"

# Set it up
install:
 - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.10.zip 
 - unzip -q go_appengine_sdk_linux_amd64-1.9.10.zip
 - ./go_appengine/goapp env
 - ./go_appengine/goapp get ...
 - mkdir $GOPATH/src/resize
 - curl https://appengine-go.googlecode.com/hg/example/moustachio/resize/resize.go > $GOPATH/src/resize/resize.go

# run build
script:
 - ./go_appengine/goapp build
 - ./go_appengine/goapp test
