language: go
go:
  - "1.3.1"

# Set it up
install:
 - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.12.zip
 - unzip -q go_appengine_sdk_linux_amd64-1.9.12
 - ./go_appengine/goapp env
 - env `./go_appengine/goapp env` mkdir $GOPATH/src/resize
 - env `./go_appengine/goapp env` curl https://appengine-go.googlecode.com/hg/example/moustachio/resize/resize.go > $GOPATH/src/resize/resize.go
 - ./go_appengine/goapp get -v github.com/icco/natnatnat

# run build
script:
 - ./go_appengine/goapp build
 - ./go_appengine/goapp test

notifications:
  email:
    on_success: never
    on_failure: change
