# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false

# https://cloud.google.com/appengine/docs/go/release-notes
# the golang version should match the version in the pkg
go:
  - "1.6.2"
env:
  - GAE_VERSION=go_appengine_sdk_linux_amd64-1.9.40
install:
 - curl -O https://storage.googleapis.com/appengine-sdks/featured/$GAE_VERSION.zip
 - unzip -q $GAE_VERSION
 - mv go_appengine ..
 - ../go_appengine/goapp env
script:
 - make test
notifications:
  email:
    on_success: never
    on_failure: change
