language: go
go:
  - "1.3.1"

# Set it up
install:
 - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.23.zip
 - unzip -q go_appengine_sdk_linux_amd64-1.9.12
 - ./go_appengine/goapp env

# run build
script:
 - ./go_appengine/goapp get -d -v ./... 
 - ./go_appengine/goapp build
 - ./go_appengine/goapp test

notifications:
  email:
    on_success: never
    on_failure: change
